#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  command:
    start: docker-compose -f poc/docker-compose/docker-compose-p4-couch.yaml up -d;sleep 3s
    end: docker-compose -f poc/docker-compose/docker-compose-p4-couch.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 1.4.4
  Size: 1 Org with 4 Peers
  Orderer: Solo
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: poc/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/f93ba26e5ee9e196fc3951f87167df9c7920bb576a080a91af647912de29a1e3_sk
      clientSignedCert:
        path: poc/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem

channels:
  mychannel:
    configBinary: poc/config/channel.tx
    created: false
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer1.org1.example.com:
        eventSource: true
      peer2.org1.example.com:
        eventSource: true
      peer3.org1.example.com:
        eventSource: true

    chaincodes:
      - id: mycc
        version: v1.0
        language: golang
        path: fabric/poc/go

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer2.org1.example.com
      - peer3.org1.example.com
    certificateAuthorities:
      - ca.example.com
    adminPrivateKey:
      path: poc/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/486dbe1920bc3d05d8813c16af3cf1893d6e876ff5d30c913494674021149fdb_sk
    signedCert:
      path: poc/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000

  peer1.org1.example.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      grpc.keepalive_time_ms: 600000

  peer2.org1.example.com:
    url: grpc://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
      grpc.keepalive_time_ms: 600000

  peer3.org1.example.com:
    url: grpc://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer3.org1.example.com
      grpc.keepalive_time_ms: 600000

certificateAuthorities:
  ca.example.com:
    url: http://localhost:7054
    httpOptions:
      verify: false
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
